apiVersion: v1
kind: ConfigMap
metadata:
  name: bestsupport-config
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1,helpdesk.example.com
  DJANGO_CSRF_TRUSTED_ORIGINS: https://helpdesk.example.com
  DJANGO_BEHIND_PROXY: "True"
  DJANGO_SESSION_COOKIE_SECURE: "True"
  DJANGO_CSRF_COOKIE_SECURE: "True"
  DJANGO_SECURE_SSL_REDIRECT: "False"
  DJANGO_SECURE_HSTS_SECONDS: "31536000"
  DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS: "True"
  DJANGO_SECURE_HSTS_PRELOAD: "True"
  DJANGO_READINESS_CHECK_MIGRATIONS: "True"
  SITE_URL: https://helpdesk.example.com
  ALLOWED_REGISTRATION_DOMAINS: bestfinance.com.np
  DEFAULT_FROM_EMAIL: helpdesk@example.com
  IT_SUPPORT_EMAIL: helpdesk@example.com
  SMTP_HOST: ""
  SMTP_PORT: "587"
  SMTP_USE_TLS: "True"
  SMTP_FROM_EMAIL: helpdesk@example.com
  POSTGRES_DB: helpdeskdb
  POSTGRES_USER: postgres
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  USE_REDIS_CHANNEL_LAYER: "True"
  REDIS_URL: redis://redis:6379/0
  MINIO_ENDPOINT_URL: http://minio:9000
  MINIO_BUCKET: bestsupport-media
  MINIO_REGION: us-east-1
  TICKET_ATTACHMENT_MAX_SIZE_MB: "20"
  MESSAGE_RETENTION_DAYS: "180"
  OPEN_TICKET_CONVERSATION_RETENTION_DAYS: "10"
  CLOSED_TICKET_CONVERSATION_RETENTION_DAYS: "10"
  TICKET_AUTO_CLOSE_DAYS: "10"
  WEBRTC_USE_HOST_TURN_FALLBACK: "False"
  WEBRTC_STUN_URLS: ""
  WEBRTC_TURN_URLS: ""
  WEBRTC_TURN_USERNAME: ""
  TURN_REALM: helpdesk.example.com
  TURN_EXTERNAL_IP: ""
  TURN_PORT: "3478"
  TURN_TLS_PORT: "5349"
  TURN_MIN_PORT: "49160"
  TURN_MAX_PORT: "49200"
