apiVersion: v1
kind: Secret
metadata:
  name: bestsupport-secrets
type: Opaque
stringData:
  DJANGO_SECRET_KEY: replace-with-a-long-random-secret
  POSTGRES_PASSWORD: replace-with-postgres-password
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: replace-with-minio-password
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""
  AD_BIND_PASSWORD: ""
  TURN_AUTH_SECRET: replace-with-turn-secret-if-you-use-coturn
