# Generated by Django 5.2.5 on 2025-09-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='user',
            new_name='created_by',
        ),
    ]
