# Generated by Django 5.2.5 on 2026-05-02 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0041_incidentreportattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='action_plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='date_of_notification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='date_of_report',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='date_time_of_detection',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='date_time_of_occurrence',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='eradication_method',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='immediate_actions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='incident_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='incident_location_ip',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='lessons_learned',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='network_impacted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='operations_impacted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='point_of_contact',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='post_recovery_verification',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='quarantine_process',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='recommendations_for_improvement',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='recovery_actions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='recovery_communication',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='recovery_timeframe',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporting_employee_contact',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporting_employee_designation',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporting_employee_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='reporting_employee_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='root_cause_analysis',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='severity_choice',
            field=models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='source_of_incident',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='systems_impacted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='unit_or_department_impacted',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='unit_or_department_requiring_notification',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticketremindersummarylog',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
