# Generated by Django 5.2.5 on 2026-05-11 18:18

import tickets.models
import tickets.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0049_remoteaccessapproval_second_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='notified_signature',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=tickets.storage.TicketImageStorage(), upload_to=tickets.models.incident_report_signature_upload_to),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='registered_signature',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=tickets.storage.TicketImageStorage(), upload_to=tickets.models.incident_report_signature_upload_to),
        ),
        migrations.AlterField(
            model_name='incidentreportattachment',
            name='file',
            field=models.FileField(max_length=255, storage=tickets.storage.TicketImageStorage(), upload_to=tickets.models.incident_report_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='incidentreportsignoff',
            name='snapshot_signature',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=tickets.storage.TicketImageStorage(), upload_to=tickets.models.incident_report_signoff_signature_upload_to),
        ),
        migrations.AlterField(
            model_name='remoteaccessapproval',
            name='access_user_signature_snapshot',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=tickets.storage.TicketImageStorage(), upload_to=tickets.models.remote_access_signature_snapshot_upload_to),
        ),
        migrations.AlterField(
            model_name='remoteaccessapproval',
            name='approved_signature_snapshot',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=tickets.storage.TicketImageStorage(), upload_to=tickets.models.remote_access_signature_snapshot_upload_to),
        ),
        migrations.AlterField(
            model_name='remoteaccessapproval',
            name='recommended_signature_snapshot',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=tickets.storage.TicketImageStorage(), upload_to=tickets.models.remote_access_signature_snapshot_upload_to),
        ),
        migrations.AlterField(
            model_name='remoteaccessapproval',
            name='requested_signature_snapshot',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=tickets.storage.TicketImageStorage(), upload_to=tickets.models.remote_access_signature_snapshot_upload_to),
        ),
        migrations.AlterField(
            model_name='remoteaccessapproval',
            name='second_recommended_signature_snapshot',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=tickets.storage.TicketImageStorage(), upload_to=tickets.models.remote_access_signature_snapshot_upload_to),
        ),
    ]
