"""
Django settings for helpdesk project.

Generated by 'django-admin startproject' using Django 2.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import json
import os
import socket


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def parse_csv_env(name, default=""):
    raw = os.getenv(name, default)
    return [item.strip() for item in raw.split(",") if item.strip()]


def load_webrtc_ice_servers():
    raw_json = os.getenv("WEBRTC_ICE_SERVERS_JSON", "").strip()
    if raw_json:
        try:
            parsed = json.loads(raw_json)
        except json.JSONDecodeError:
            parsed = []

        servers = []
        if isinstance(parsed, list):
            for item in parsed:
                if not isinstance(item, dict):
                    continue
                urls = item.get("urls")
                if isinstance(urls, str):
                    urls_value = urls.strip()
                elif isinstance(urls, list):
                    urls_value = [value.strip() for value in urls if isinstance(value, str) and value.strip()]
                else:
                    continue
                if not urls_value:
                    continue

                server = {"urls": urls_value}
                username = item.get("username")
                credential = item.get("credential")
                credential_type = item.get("credentialType")

                if isinstance(username, str) and username.strip():
                    server["username"] = username.strip()
                if isinstance(credential, str) and credential:
                    server["credential"] = credential
                if isinstance(credential_type, str) and credential_type.strip():
                    server["credentialType"] = credential_type.strip()
                servers.append(server)
        return servers

    stun_urls = parse_csv_env("WEBRTC_STUN_URLS")
    turn_urls = parse_csv_env("WEBRTC_TURN_URLS")
    turn_username = os.getenv("WEBRTC_TURN_USERNAME", "").strip()
    turn_password = os.getenv("WEBRTC_TURN_PASSWORD", "")
    turn_credential_type = os.getenv("WEBRTC_TURN_CREDENTIAL_TYPE", "").strip()

    servers = []
    if stun_urls:
        servers.append({"urls": stun_urls if len(stun_urls) > 1 else stun_urls[0]})
    if turn_urls:
        turn_server = {"urls": turn_urls if len(turn_urls) > 1 else turn_urls[0]}
        if turn_username:
            turn_server["username"] = turn_username
        if turn_password:
            turn_server["credential"] = turn_password
        if turn_credential_type:
            turn_server["credentialType"] = turn_credential_type
        servers.append(turn_server)
    return servers


def env_bool(name, default=False):
    return os.getenv(name, "true" if default else "false").strip().lower() == "true"


def get_local_debug_hosts():
    hosts = {"127.0.0.1", "localhost"}
    try:
        hostname = socket.gethostname()
        if hostname:
            hosts.add(hostname)
        fqdn = socket.getfqdn()
        if fqdn:
            hosts.add(fqdn)
        for item in socket.getaddrinfo(hostname, None):
            ip = item[4][0]
            if ":" not in ip:
                hosts.add(ip)
    except Exception:
        pass
    return hosts


def build_csrf_trusted_origins(hosts):
    origins = []
    for host in hosts:
        if host in {"*", "0.0.0.0"}:
            continue
        origins.append(f"http://{host}")
        origins.append(f"https://{host}")
    return origins


def load_local_env(path):
    if not os.path.exists(path):
        return
    with open(path, "r", encoding="utf-8") as env_file:
        for raw_line in env_file:
            line = raw_line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip())


load_local_env(os.path.join(BASE_DIR, ".env"))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() == 'true'

# Registration settings
def parse_csv_env_lower(name, default=""):
    return [item.strip().lower() for item in parse_csv_env(name, default) if item.strip()]


_allowed_domains = parse_csv_env_lower("ALLOWED_REGISTRATION_DOMAINS")
if not _allowed_domains:
    _single = os.getenv("ALLOWED_REGISTRATION_EMAIL_DOMAIN", "bestfinance.com.np").strip().lower()
    _allowed_domains = [_single] if _single else []

ALLOWED_REGISTRATION_EMAIL_DOMAINS = _allowed_domains
SIGNUP_LINK_MAX_AGE_SECONDS = int(os.getenv("SIGNUP_LINK_MAX_AGE_SECONDS", "86400"))

ALLOWED_HOSTS = parse_csv_env('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost')
if DEBUG:
    ALLOWED_HOSTS = sorted(set(ALLOWED_HOSTS).union(get_local_debug_hosts()))

CSRF_TRUSTED_ORIGINS = parse_csv_env('DJANGO_CSRF_TRUSTED_ORIGINS')
if DEBUG and not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = build_csrf_trusted_origins(ALLOWED_HOSTS)


# Application definition

INSTALLED_APPS = [
    'accounts',
    'tickets',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'helpdesk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        ##'DIRS': [],
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'helpdesk.wsgi.application'
ASGI_APPLICATION = 'helpdesk.asgi.application'

USE_REDIS_CHANNEL_LAYER = os.getenv('USE_REDIS_CHANNEL_LAYER', 'False').lower() == 'true'
REDIS_URL = os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0')

if USE_REDIS_CHANNEL_LAYER:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'helpdeskdb'),
        'USER': os.getenv('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
        'HOST': os.getenv('POSTGRES_HOST', 'localhost'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        "OPTIONS": {"min_length": 9},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        "NAME": "accounts.password_validators.DisallowEmailDomainInPasswordValidator",
    },
    {
        "NAME": "accounts.password_validators.DisallowSequenceInPasswordValidator",
        "OPTIONS": {"sequences": ["123"]},
    },
    {
        "NAME": "accounts.password_validators.RecentPasswordReuseValidator",
        "OPTIONS": {"history_size": 5},
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_L10N = True

USE_TZ = True


AUTH_USER_MODEL = 'accounts.CustomUser'

LOGIN_REDIRECT_URL = 'dashboard'  # Where to redirect after login
LOGOUT_REDIRECT_URL = 'login'     # Where to redirect after logout
LOGIN_URL = 'login'               # The login page URL

# Email settings (SMTP if configured, else console)
SMTP_HOST = os.getenv("SMTP_HOST", "").strip()
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USERNAME = os.getenv("SMTP_USERNAME", "").strip()
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
SMTP_USE_TLS = os.getenv("SMTP_USE_TLS", "True").lower() == "true"
SMTP_USE_SSL = os.getenv("SMTP_USE_SSL", "False").lower() == "true"
SMTP_FROM_EMAIL = os.getenv("SMTP_FROM_EMAIL", "").strip()

if SMTP_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = SMTP_HOST
    EMAIL_PORT = SMTP_PORT
    EMAIL_HOST_USER = SMTP_USERNAME
    EMAIL_HOST_PASSWORD = SMTP_PASSWORD
    EMAIL_USE_TLS = SMTP_USE_TLS
    EMAIL_USE_SSL = SMTP_USE_SSL
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

DEFAULT_FROM_EMAIL = SMTP_FROM_EMAIL or os.getenv('DEFAULT_FROM_EMAIL', 'helpdesk@bestfinance.com.np')
IT_SUPPORT_EMAIL = os.getenv('IT_SUPPORT_EMAIL', 'helpdesk@bestfinance.com.np')
MESSAGE_RETENTION_DAYS = int(os.getenv('MESSAGE_RETENTION_DAYS', '180'))
OPEN_TICKET_CONVERSATION_RETENTION_DAYS = int(os.getenv("OPEN_TICKET_CONVERSATION_RETENTION_DAYS", "10"))
TICKET_AUTO_CLOSE_DAYS = int(os.getenv("TICKET_AUTO_CLOSE_DAYS", "10"))
CLOSED_TICKET_CONVERSATION_RETENTION_DAYS = int(
    os.getenv("CLOSED_TICKET_CONVERSATION_RETENTION_DAYS", "10")
)
GROUP_MAILBOX_EMAILS = parse_csv_env_lower(
    "GROUP_MAILBOX_EMAILS",
    "it@bestfinance.com.np,hr@bestfinance.com.np,cad@bestfinance.com.np",
)
WEBRTC_ICE_SERVERS = load_webrtc_ice_servers()
WEBRTC_USE_HOST_TURN_FALLBACK = env_bool("WEBRTC_USE_HOST_TURN_FALLBACK", default=True)
WEBRTC_STUN_PORT = int(os.getenv("WEBRTC_STUN_PORT", "3478"))
WEBRTC_TURN_PORT = int(os.getenv("WEBRTC_TURN_PORT", "3478"))
WEBRTC_TURNS_PORT = int(os.getenv("WEBRTC_TURNS_PORT", "5349"))
WEBRTC_TURN_USERNAME = os.getenv("WEBRTC_TURN_USERNAME", "").strip()
WEBRTC_TURN_PASSWORD = os.getenv("WEBRTC_TURN_PASSWORD", "")
WEBRTC_TURN_AUTH_SECRET = os.getenv("WEBRTC_TURN_AUTH_SECRET", os.getenv("TURN_AUTH_SECRET", "")).strip()
WEBRTC_TURN_CREDENTIAL_TTL_SECONDS = int(os.getenv("WEBRTC_TURN_CREDENTIAL_TTL_SECONDS", "3600"))
WEBRTC_TURN_CREDENTIAL_TYPE = os.getenv("WEBRTC_TURN_CREDENTIAL_TYPE", "").strip()
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

SECURE_SSL_REDIRECT = os.getenv('DJANGO_SECURE_SSL_REDIRECT', 'False').lower() == 'true'
SESSION_COOKIE_SECURE = os.getenv('DJANGO_SESSION_COOKIE_SECURE', 'False').lower() == 'true'
CSRF_COOKIE_SECURE = os.getenv('DJANGO_CSRF_COOKIE_SECURE', 'False').lower() == 'true'
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False').lower() == 'true'
SECURE_HSTS_PRELOAD = os.getenv('DJANGO_SECURE_HSTS_PRELOAD', 'False').lower() == 'true'
X_FRAME_OPTIONS = os.getenv('DJANGO_X_FRAME_OPTIONS', 'DENY')

# If Django is behind a reverse proxy (nginx) terminating TLS, trust forwarded scheme/host.
# Required for correct CSRF behavior over HTTPS when using X-Forwarded-Proto.
DJANGO_BEHIND_PROXY = os.getenv("DJANGO_BEHIND_PROXY", "True").lower() == "true"
if DJANGO_BEHIND_PROXY:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True

# MinIO (S3-compatible) storage for ticket chat attachments (proxied via Django)
MINIO_ENDPOINT_URL = os.getenv("MINIO_ENDPOINT_URL", "").strip()
MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY", os.getenv("MINIO_ROOT_USER", "")).strip()
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY", os.getenv("MINIO_ROOT_PASSWORD", "")).strip()
MINIO_BUCKET = os.getenv("MINIO_BUCKET", "bestsupport-media").strip()
MINIO_REGION = os.getenv("MINIO_REGION", "us-east-1").strip() or "us-east-1"
_ticket_attachment_max_bytes = os.getenv("TICKET_ATTACHMENT_MAX_BYTES", "").strip()
if _ticket_attachment_max_bytes:
    TICKET_ATTACHMENT_MAX_BYTES = int(_ticket_attachment_max_bytes)
else:
    _size_mb = os.getenv("TICKET_ATTACHMENT_MAX_SIZE_MB", "").strip()
    if _size_mb:
        _normalized = _size_mb.lower().replace(" ", "")
        if _normalized.endswith("mb"):
            _normalized = _normalized[:-2]
        TICKET_ATTACHMENT_MAX_BYTES = int(float(_normalized) * 1024 * 1024)
    else:
        TICKET_ATTACHMENT_MAX_BYTES = 20 * 1024 * 1024
