# Generated by Django 5.2.5 on 2026-05-11 18:18

import accounts.models
import tickets.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_signature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='signature_image',
            field=models.ImageField(blank=True, max_length=255, null=True, storage=tickets.storage.TicketImageStorage(), upload_to=accounts.models.user_signature_upload_to),
        ),
    ]
